&ifndef MODULELIST
&define MODULELIST

PUBLIC
   CONSTANT

        MODULE_AUDIT   STRING = "audit"
      , MODULE_BOM     STRING = "bom"
      , MODULE_DC      STRING = "dc"
      , MODULE_EXP     STRING = "exp"
      , MODULE_FORMS   STRING = "forms"
      , MODULE_GOLDEN  STRING = "golden"
      , MODULE_IMDB    STRING = "imdb"
      , MODULE_IS      STRING = "is"
      , MODULE_KB      STRING = "kb"
      , MODULE_LIB     STRING = "lib"
      , MODULE_NL      STRING = "nl"
      , MODULE_PGLIB   STRING = "pglib"
      , MODULE_PL      STRING = "pl"
      , MODULE_POP     STRING = "pop"
      , MODULE_SCRIPT  STRING = "script"
      , MODULE_SFDC    STRING = "sfdc"
      , MODULE_SL      STRING = "sl"
      , MODULE_SOP     STRING = "sop"
      , MODULE_SRCHLIB STRING = "srchlib"
      , MODULE_STM     STRING = "stm"
      , MODULE_STOCK   STRING = "stock"
      , MODULE_STUB    STRING = "stub"
      , MODULE_SYS     STRING = "sys"
      , MODULE_SYSTEM  STRING = "system"
      , MODULE_TSM     STRING = "tsm"
      , MODULE_WOP     STRING = "wop"
      , MODULE_WS      STRING = "ws"

&endif
